<?php

/**
 * @file
 * Custom helper functions for Omega Five.
 *
 * This file contains the primary helper functions used for the Omega Five base
 * theme.
 */

use Drupal\Core\Url;

/**
 * Implements hook_system_themes_page_alter() for theme page form.
 *
 * This is required in module form since Omega is likely (almost always) not
 * set as admin theme so that we can manipulate the theme listing page a bit.
 */
function omega_tools_system_themes_page_alter(array &$theme_groups) {
  foreach ($theme_groups as $state => &$group) {
    /** @var Drupal\Core\Extension\Extension $theme */
    foreach ($theme_groups[$state] as $k => $theme) {
      $forceExport = isset($theme->info['force_export']) ? $theme->info['force_export'] : FALSE;
      // Forced export in .info.yml settings, let's alter the Settings link.
      if ($forceExport) {
        foreach ($theme->operations as $k => $operation) {
          /* @var Drupal\Core\StringTranslation\TranslatableMarkup $operation['title'] */
          if ($operation['title']->render() == 'Settings') {
            // Let's completely reset the 'Settings' link as this omega subtheme
            // has no settings, so display the export/subtheme functionality.
            $theme->operations[$k] = [
              'title' => t('Create Subtheme'),
              'url' => Url::fromRoute('system.theme_settings_theme', ['theme' => $theme->getName()]),
              'attributes' => ['title' => t('Create a new subtheme of the @theme theme', ['@theme' => $theme->info['name']])],
            ];
          }
        }
      }

      /*
       * Attempt to hide themes we don't want to be enabled, and should be
       * hidden from the administrative interface.
       *
       * @todo: Ensure this can be configured.
       */

      // Array of theme machine names to be hidden.
      $hidden_themes = [
        'bartik',
        'stark',
      ];

      if (in_array($theme->getName(), $hidden_themes)) {
        // Remove it from the array of items before rendering page.
        unset($theme_groups[$state][$k]);
      }

      /*
       * Let's add some useful links just for the Omega theme.
       */
      if ($theme->getName() == 'omega') {
        // Link to Project Page.
        $theme->operations[] = [
          'title' => t('Project Page'),
          'url' => Url::fromUri('https://drupal.org/project/omega', [
            'attributes' => ['target' => '_blank'],
          ]),
        ];
        // Link to Issue Queue.
        $theme->operations[] = [
          'title' => t('Issue Queue'),
          'url' => Url::fromUri('https://drupal.org/project/issues/omega', [
            'attributes' => ['target' => '_blank'],
          ]),
        ];
        // Link to GitHub project.
        $theme->operations[] = [
          'title' => t('GitHub'),
          'url' => Url::fromUri('https://github.com/himerus/omega', [
            'attributes' => ['target' => '_blank'],
          ]),
        ];
      }
    }
  }
}
