<?php
// $Id: preprocess-zone.inc,v 1.1.2.5 2010/11/29 16:25:34 himerus Exp $

/**
 * @file
 * Contents of omega_preprocess_zone().
 * 
 * The functionality here is actually quite simple, applying to the container
 * regions of the 960 grid. 
 * 
 * There is not much processing needed to be done to the container elements
 * excluding checking for the appropriate classes/id to assign to the element
 */

