name = epiqo
description = Default layout for epiqo distributions.

regions[navigation] = Navigation
regions[banner] = Banner
regions[search] = Search
regions[preface] = Preface
regions[content] = Content
regions[postscript] = Postscript
regions[footer] = Footer
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar

stylesheets[all][] = css/epiqo.layout.css
stylesheets[all][] = css/epiqo.styles.css
scripts[] = js/epiqo.layout.js

preview = preview.png
